/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Maintenance6RouteImport } from './routes/maintenance6'
import { Route as Maintenance5RouteImport } from './routes/maintenance5'
import { Route as Maintenance4RouteImport } from './routes/maintenance4'
import { Route as Maintenance2RouteImport } from './routes/maintenance2'
import { Route as Anne6RouteImport } from './routes/anne6'
import { Route as Anne5RouteImport } from './routes/anne5'
import { Route as Anne4RouteImport } from './routes/anne4'
import { Route as Anne3RouteImport } from './routes/anne3'
import { Route as Anne2RouteImport } from './routes/anne2'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnneIndexRouteImport } from './routes/anne.index'
import { Route as AnnePaymentSuccessRouteImport } from './routes/anne.payment-success'
import { Route as AnneFpdUpsellRouteImport } from './routes/anne.fpd.upsell'
import { Route as AnneFpdMaintenanceRouteImport } from './routes/anne.fpd.maintenance'
import { Route as AnneFpdDonationRouteImport } from './routes/anne.fpd.donation'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicHooksProcessScheduledChargesRouteImport } from './routes/api/public/hooks/process-scheduled-charges'

const Maintenance6Route = Maintenance6RouteImport.update({
  id: '/maintenance6',
  path: '/maintenance6',
  getParentRoute: () => rootRouteImport,
} as any)
const Maintenance5Route = Maintenance5RouteImport.update({
  id: '/maintenance5',
  path: '/maintenance5',
  getParentRoute: () => rootRouteImport,
} as any)
const Maintenance4Route = Maintenance4RouteImport.update({
  id: '/maintenance4',
  path: '/maintenance4',
  getParentRoute: () => rootRouteImport,
} as any)
const Maintenance2Route = Maintenance2RouteImport.update({
  id: '/maintenance2',
  path: '/maintenance2',
  getParentRoute: () => rootRouteImport,
} as any)
const Anne6Route = Anne6RouteImport.update({
  id: '/anne6',
  path: '/anne6',
  getParentRoute: () => rootRouteImport,
} as any)
const Anne5Route = Anne5RouteImport.update({
  id: '/anne5',
  path: '/anne5',
  getParentRoute: () => rootRouteImport,
} as any)
const Anne4Route = Anne4RouteImport.update({
  id: '/anne4',
  path: '/anne4',
  getParentRoute: () => rootRouteImport,
} as any)
const Anne3Route = Anne3RouteImport.update({
  id: '/anne3',
  path: '/anne3',
  getParentRoute: () => rootRouteImport,
} as any)
const Anne2Route = Anne2RouteImport.update({
  id: '/anne2',
  path: '/anne2',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnneIndexRoute = AnneIndexRouteImport.update({
  id: '/anne/',
  path: '/anne/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnePaymentSuccessRoute = AnnePaymentSuccessRouteImport.update({
  id: '/anne/payment-success',
  path: '/anne/payment-success',
  getParentRoute: () => rootRouteImport,
} as any)
const AnneFpdUpsellRoute = AnneFpdUpsellRouteImport.update({
  id: '/anne/fpd/upsell',
  path: '/anne/fpd/upsell',
  getParentRoute: () => rootRouteImport,
} as any)
const AnneFpdMaintenanceRoute = AnneFpdMaintenanceRouteImport.update({
  id: '/anne/fpd/maintenance',
  path: '/anne/fpd/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const AnneFpdDonationRoute = AnneFpdDonationRouteImport.update({
  id: '/anne/fpd/donation',
  path: '/anne/fpd/donation',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksProcessScheduledChargesRoute =
  ApiPublicHooksProcessScheduledChargesRouteImport.update({
    id: '/api/public/hooks/process-scheduled-charges',
    path: '/api/public/hooks/process-scheduled-charges',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anne2': typeof Anne2Route
  '/anne3': typeof Anne3Route
  '/anne4': typeof Anne4Route
  '/anne5': typeof Anne5Route
  '/anne6': typeof Anne6Route
  '/maintenance2': typeof Maintenance2Route
  '/maintenance4': typeof Maintenance4Route
  '/maintenance5': typeof Maintenance5Route
  '/maintenance6': typeof Maintenance6Route
  '/anne/payment-success': typeof AnnePaymentSuccessRoute
  '/anne/': typeof AnneIndexRoute
  '/anne/fpd/donation': typeof AnneFpdDonationRoute
  '/anne/fpd/maintenance': typeof AnneFpdMaintenanceRoute
  '/anne/fpd/upsell': typeof AnneFpdUpsellRoute
  '/api/public/hooks/process-scheduled-charges': typeof ApiPublicHooksProcessScheduledChargesRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anne2': typeof Anne2Route
  '/anne3': typeof Anne3Route
  '/anne4': typeof Anne4Route
  '/anne5': typeof Anne5Route
  '/anne6': typeof Anne6Route
  '/maintenance2': typeof Maintenance2Route
  '/maintenance4': typeof Maintenance4Route
  '/maintenance5': typeof Maintenance5Route
  '/maintenance6': typeof Maintenance6Route
  '/anne/payment-success': typeof AnnePaymentSuccessRoute
  '/anne': typeof AnneIndexRoute
  '/anne/fpd/donation': typeof AnneFpdDonationRoute
  '/anne/fpd/maintenance': typeof AnneFpdMaintenanceRoute
  '/anne/fpd/upsell': typeof AnneFpdUpsellRoute
  '/api/public/hooks/process-scheduled-charges': typeof ApiPublicHooksProcessScheduledChargesRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anne2': typeof Anne2Route
  '/anne3': typeof Anne3Route
  '/anne4': typeof Anne4Route
  '/anne5': typeof Anne5Route
  '/anne6': typeof Anne6Route
  '/maintenance2': typeof Maintenance2Route
  '/maintenance4': typeof Maintenance4Route
  '/maintenance5': typeof Maintenance5Route
  '/maintenance6': typeof Maintenance6Route
  '/anne/payment-success': typeof AnnePaymentSuccessRoute
  '/anne/': typeof AnneIndexRoute
  '/anne/fpd/donation': typeof AnneFpdDonationRoute
  '/anne/fpd/maintenance': typeof AnneFpdMaintenanceRoute
  '/anne/fpd/upsell': typeof AnneFpdUpsellRoute
  '/api/public/hooks/process-scheduled-charges': typeof ApiPublicHooksProcessScheduledChargesRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anne2'
    | '/anne3'
    | '/anne4'
    | '/anne5'
    | '/anne6'
    | '/maintenance2'
    | '/maintenance4'
    | '/maintenance5'
    | '/maintenance6'
    | '/anne/payment-success'
    | '/anne/'
    | '/anne/fpd/donation'
    | '/anne/fpd/maintenance'
    | '/anne/fpd/upsell'
    | '/api/public/hooks/process-scheduled-charges'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anne2'
    | '/anne3'
    | '/anne4'
    | '/anne5'
    | '/anne6'
    | '/maintenance2'
    | '/maintenance4'
    | '/maintenance5'
    | '/maintenance6'
    | '/anne/payment-success'
    | '/anne'
    | '/anne/fpd/donation'
    | '/anne/fpd/maintenance'
    | '/anne/fpd/upsell'
    | '/api/public/hooks/process-scheduled-charges'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/anne2'
    | '/anne3'
    | '/anne4'
    | '/anne5'
    | '/anne6'
    | '/maintenance2'
    | '/maintenance4'
    | '/maintenance5'
    | '/maintenance6'
    | '/anne/payment-success'
    | '/anne/'
    | '/anne/fpd/donation'
    | '/anne/fpd/maintenance'
    | '/anne/fpd/upsell'
    | '/api/public/hooks/process-scheduled-charges'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Anne2Route: typeof Anne2Route
  Anne3Route: typeof Anne3Route
  Anne4Route: typeof Anne4Route
  Anne5Route: typeof Anne5Route
  Anne6Route: typeof Anne6Route
  Maintenance2Route: typeof Maintenance2Route
  Maintenance4Route: typeof Maintenance4Route
  Maintenance5Route: typeof Maintenance5Route
  Maintenance6Route: typeof Maintenance6Route
  AnnePaymentSuccessRoute: typeof AnnePaymentSuccessRoute
  AnneIndexRoute: typeof AnneIndexRoute
  AnneFpdDonationRoute: typeof AnneFpdDonationRoute
  AnneFpdMaintenanceRoute: typeof AnneFpdMaintenanceRoute
  AnneFpdUpsellRoute: typeof AnneFpdUpsellRoute
  ApiPublicHooksProcessScheduledChargesRoute: typeof ApiPublicHooksProcessScheduledChargesRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/maintenance6': {
      id: '/maintenance6'
      path: '/maintenance6'
      fullPath: '/maintenance6'
      preLoaderRoute: typeof Maintenance6RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance5': {
      id: '/maintenance5'
      path: '/maintenance5'
      fullPath: '/maintenance5'
      preLoaderRoute: typeof Maintenance5RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance4': {
      id: '/maintenance4'
      path: '/maintenance4'
      fullPath: '/maintenance4'
      preLoaderRoute: typeof Maintenance4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance2': {
      id: '/maintenance2'
      path: '/maintenance2'
      fullPath: '/maintenance2'
      preLoaderRoute: typeof Maintenance2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anne6': {
      id: '/anne6'
      path: '/anne6'
      fullPath: '/anne6'
      preLoaderRoute: typeof Anne6RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anne5': {
      id: '/anne5'
      path: '/anne5'
      fullPath: '/anne5'
      preLoaderRoute: typeof Anne5RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anne4': {
      id: '/anne4'
      path: '/anne4'
      fullPath: '/anne4'
      preLoaderRoute: typeof Anne4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anne3': {
      id: '/anne3'
      path: '/anne3'
      fullPath: '/anne3'
      preLoaderRoute: typeof Anne3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anne2': {
      id: '/anne2'
      path: '/anne2'
      fullPath: '/anne2'
      preLoaderRoute: typeof Anne2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anne/': {
      id: '/anne/'
      path: '/anne'
      fullPath: '/anne/'
      preLoaderRoute: typeof AnneIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anne/payment-success': {
      id: '/anne/payment-success'
      path: '/anne/payment-success'
      fullPath: '/anne/payment-success'
      preLoaderRoute: typeof AnnePaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anne/fpd/upsell': {
      id: '/anne/fpd/upsell'
      path: '/anne/fpd/upsell'
      fullPath: '/anne/fpd/upsell'
      preLoaderRoute: typeof AnneFpdUpsellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anne/fpd/maintenance': {
      id: '/anne/fpd/maintenance'
      path: '/anne/fpd/maintenance'
      fullPath: '/anne/fpd/maintenance'
      preLoaderRoute: typeof AnneFpdMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anne/fpd/donation': {
      id: '/anne/fpd/donation'
      path: '/anne/fpd/donation'
      fullPath: '/anne/fpd/donation'
      preLoaderRoute: typeof AnneFpdDonationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/process-scheduled-charges': {
      id: '/api/public/hooks/process-scheduled-charges'
      path: '/api/public/hooks/process-scheduled-charges'
      fullPath: '/api/public/hooks/process-scheduled-charges'
      preLoaderRoute: typeof ApiPublicHooksProcessScheduledChargesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Anne2Route: Anne2Route,
  Anne3Route: Anne3Route,
  Anne4Route: Anne4Route,
  Anne5Route: Anne5Route,
  Anne6Route: Anne6Route,
  Maintenance2Route: Maintenance2Route,
  Maintenance4Route: Maintenance4Route,
  Maintenance5Route: Maintenance5Route,
  Maintenance6Route: Maintenance6Route,
  AnnePaymentSuccessRoute: AnnePaymentSuccessRoute,
  AnneIndexRoute: AnneIndexRoute,
  AnneFpdDonationRoute: AnneFpdDonationRoute,
  AnneFpdMaintenanceRoute: AnneFpdMaintenanceRoute,
  AnneFpdUpsellRoute: AnneFpdUpsellRoute,
  ApiPublicHooksProcessScheduledChargesRoute:
    ApiPublicHooksProcessScheduledChargesRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
